server.port: 8081

camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest # The URL pointing to the Camunda Platform Runtime REST API
  worker-id: charge-card-worker-spring-boot # Identifies the worker towards the Engine

logging.level.org.camunda.bpm.client: info
